config/routes.rb
Rails.application.routes.draw do

  root 'collections#new'

  resources :collections

  get '/collections/:id' => 'collections#show'

  post '/collections/:id/send_email' => 'collections#send_email', as: :send_email

end

app/models/collection.rb
class Collection < ActiveRecord::Base

	# Instances of this class should have instances of
		# NewsItem
		# WikiItem
		# MemeItem
	#Instances of this class will make up the content on the custom report page

	belongs_to :user
	has_many :news_items
	has_many :wiki_event_items
	has_many :wiki_birth_items
	has_many :wiki_holiday_items
  has_many :giphy_items
	# has_many :meme_items

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

	def new
		@collection = Collection.new
		render :new
	end
	
	def create
		date = params[:collection][:date]

		@collection = Collection.new(:date => date)
		@collection.giphy_items.build(:date => date)
		@collection.wiki_event_items = WikiEventItem.new_from_date(date)
		@collection.wiki_birth_items = WikiBirthItem.new_from_date(date)
		@collection.wiki_holiday_items = WikiHolidayItem.new_from_date(date)
		@collection.news_items = NewsItem.new_from_date(date)
		@collection.to_name = params[:collection][:to_name]
		
		@collection.save

		redirect_to collection_path(@collection.id)
	end

	def show
		find_collection
	end

	def update
		find_collection
		create
	end

	def send_email
		find_collection
		@collection.update(collection_params)
		CollectionMailer.gift_email(@collection).deliver_now
		flash[:notice] = "Email Sent!"
		redirect_to collection_path(@collection.id)
	end

	#----- HELPERS
	private
	
	def find_collection
		@collection = Collection.find(params[:id])
	end

		def collection_params
			params.require(:collection).permit(:to_name, :to_email, :from_name, :from_email)
		end
	
end

app/views/collections/new.html.erb
<div class="balloons-background-image"></div>

  <div class="balloons-background-image"></div>
    <div class="jumbotron">
      <h1>Today is the Day!</h1>
      <p>
      <h2>please enter a birthdate!</h2>
      <br>
      <%= form_for @collection do |f| %>
      <%= f.text_field :to_name, :placeholder => " Name" %>
      <%= f.date_field :date %>
      <%= f.submit "submit", :class => "btn btn-primary" %>
      
    <% end %>
      </p>
      
    </div>
    <br>
    <div class="jumbotron-2">
      <h3>Clicking submit will take you to a customized birthday time capsule.</h3>
      <h3>After your review it fill out the email form and send it to a friend!</h3>
    </div>
  

app/views/collections/show.html.erb
<div class="balloons-background-image"></div>


<div class="smallertron">
  <h1>Happy Birthday <%="#{@collection.to_name.titleize}"%>!!!!!!</h1>
</div>
<br>
<div class="date-box">
  <h3><%= @collection.date.to_formatted_s(:long_ordinal)[/[^,]+/]%> is the day!</h3>
</div>

<% if flash[:notice] %>
<div class="notice-box"><h3><strong><%= flash[:notice] %></strong></h3></div>
<% end %>



<div class='refresh-box'>
  <%= link_to "Click to reload new events, births and holidays!", collections_path(:collection => {:to_name => @collection.to_name, :date => @collection.date}), :method => "POST", :class => "btn btn-primary" %>
</div>

<div class="events-box">
  <h3><strong>Events</strong></h3>
  <ul>
    <% @collection.wiki_event_items.each do |attr| %>
    <% if attr.event.gsub("&ndash;",":") %>
    <li><h4><%= attr.event.gsub("&ndash;",":")[0...-2] %></h4></li>
    <% end %>
    <% end %>
  </ul>
</div>
<br>

<div class="births-box">
  <h3><strong>Significant Births</strong></h3>
  <ul>
    <% @collection.wiki_birth_items.each do |attr| %>
    <% if attr.birth.gsub("&ndash;",":") %>
    <li><h4><%= attr.birth.gsub("&ndash;",":")[0...-2] %></h4></li>
    <% end %>
    <% end %>
  </ul>
</div>

<div class="col-md-6">

  <%= form_for(@collection, url: "/collections/#{@collection.id}/send_email", html: {method: "post"}) do |f| %> 
    
  <div class="form-group">
    <%= f.label :to_name,  "Whose day is it? Enter their name here." %>
    <%= f.text_field :to_name, {:class => "form-control"}%><br>
  </div>
  <div class="form-group">
    <%= f.label :to_email, :value => "What e-mail should we send it to?" %>
    <%= f.text_field :to_email, {:class => "form-control"} %><br>
  </div>
  <div class="form-group">
    <%= f.label :from_name, :value => "What is your name?" %>
    <%= f.text_field :from_name, {:class => "form-control"} %><br>
  </div>
  <div class="form-group">  
    <%= f.label :from_email, :value => "What is your e-mail address?" %>
    <%= f.text_field :from_email, {:class => "form-control"} %><br>
  </div>
    <%= f.submit "Send E-mail!", :class => "btn btn-primary" %>
    <% end %>
  
</div>
<br>
<div class="first-giphy-box">
  <iframe src="//giphy.com/embed/tnD8af8doAk1O?html5=true" width="420" height="301" frameBorder="0" webkitAllowFullScreen     mozallowfullscreen allowFullScreen></iframe>
</div>
<br>

<div class="holidays-box">
  <h3><strong>Holidays and Observances</strong></h3>
  <ul>
    <% @collection.wiki_holiday_items.each do |attr| %>
    <li><h4><%= "#{attr.holiday[0...-2]}" %></h4></li>
    <% end %>

  </ul>
</div>
<br>
<br>
<br>

<% if !@collection.news_items.empty? %>
<div class="events-box">
  <h2>New York Times headlines from the day you were born!</h2><br>
  <ul>
   <% @collection.news_items.each do |news_item| %>
   <li><h4><strong><%= "#{news_item.headline}" %></strong>:</h4> <h5><%="#{news_item.snippet}" %></h5><h5><a href= "<%"#{news_item.link.html_safe}"%>"><p><%="#{news_item.link.html_safe}"%></a></h5></li><br><p>
   <% end %>
 </ul>
</div>
<% end %>
<br>

<div class="gif-smallertron">
  <h1>MORE GIPHY'S!!!!</h1>
</div>

<div class="left-giphy-box">
  <iframe src="//giphy.com/embed/7JsQ5EQTZlgHe?html5=true" width="480" height="270" frameBorder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</div>

<!-- <div class="right-giphy-box">
  <video autoplay loop> -->
    <!-- <source src= <%#= @collection.giphy_items.first.api_call %> /> -->
<!--   </video>
</div>
<div class="left-giphy-box">
  <video autoplay loop> -->
    <!-- <source src=<%#= @collection.giphy_items.first.api_call %> /> -->
  <!-- </video>
</div>
<div class="right-giphy-box">
  <video autoplay loop> -->
    <!-- <source src=<%#= @collection.giphy_items.first.api_call %> /> -->
  <!-- </video>
</div> -->
<!-- <div class="left-giphy-box">
  <video autoplay loop>
    <source src=<%#= @collection.giphy_items.first.api_call %> />
  </video>
</div>
<div class="right-giphy-box">
  <video autoplay loop>
    <source src=<%#= @collection.giphy_items.first.api_call %> />
  </video>
</div>
<div class="left-giphy-box">
  <video autoplay loop>
    <source src=<%#= @collection.giphy_items.first.api_call %> />
  </video>
</div>
<div class="right-giphy-box">
  <video autoplay loop>
    <source src=<%#= @collection.giphy_items.first.api_call %> />
  </video>
</div> -->


<!-- # @collection.giphy_items.first.api_call -->